export { default as HomeView } from "./HomeView.vue"
export { default as RegistView } from "./RegistView.vue"
export { default as LoginView } from "./LoginView.vue"
export { default as ArticleDetailView } from "./ArticleDetailView.vue"
export { default as CreateArticleView } from "./CreateFormView.vue"